# Generated by Django 4.0.2 on 2022-07-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('bajada', models.CharField(max_length=300)),
                ('descripcion', models.TextField(default='')),
                ('lugar', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='produccion')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='produccion')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='produccion')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='produccion')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='produccion')),
                ('anio', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
    ]
