# Generated by Django 4.0.2 on 2022-06-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_alter_obra_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
    ]
