# Generated by Django 4.0.2 on 2022-06-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_descripcion_alter_obra_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='bajada',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='obra',
            name='lugar',
            field=models.CharField(default='Ushuaia', max_length=100),
        ),
    ]
