# Generated by Django 4.0.2 on 2022-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_obra_anio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['-anio']},
        ),
        migrations.AddField(
            model_name='obra',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
        migrations.AddField(
            model_name='obra',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
        migrations.AddField(
            model_name='obra',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
        migrations.AddField(
            model_name='obra',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
    ]
